# fly.toml app configuration file generated for ajl-agent on 2026-02-23T17:38:44-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ajl-agent'
primary_region = 'ord'

[build]
  dockerfile = 'Dockerfile'

[env]
  ALLOWED_ORIGINS = 'https://aujourlejour.xyz,https://www.aujourlejour.xyz'
  PORT = '8080'

[[mounts]]
  source = 'ajl_agent_data'
  destination = '/data'

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
